### ISSUE TITLE
Crash when Launching Game

### ISSUE THREAD

**Issue by emoace** [LambdAurora/AurorasDecorations#10]
Attached is the crash report: 
[crash-2021-07-27_15.17.37-client.txt](https://github.com/LambdAurora/AurorasDecorations/files/6888512/crash-2021-07-27_15.17.37-client.txt)

**Comment by LambdAurora** [comment]
bbe12e7 might fix it.

**Comment by emoace** [comment]
Yes that fixed it!  However there are some other bugs I encountered that I will catalog with separate issues.
