### ISSUE TITLE
Install the mod

### ISSUE THREAD

**Issue by Razoreanna** [LambdAurora/AurorasDecorations#17]
Ok i'm not sure if it's here i need to post my question. But how to install the mod, because he is .zip i don't know what to do?

**Comment by TofuHell** [comment]
Friend go to command prompt and then gp tp the downloaded file directory, then type gradlew build and wait for it to be finished. go to Build/libs and the first jar folder do that.

**Comment by Razoreanna** [comment]
> 

thanks you for,the answer
