### ISSUE TITLE
Gradlew build won't build jar

### ISSUE THREAD

**Issue by gokayerez** [LambdAurora/AurorasDecorations#19]
Hello, running 'gradlew build' doesn't work. It's telling me that release version 17 isn't supported. When I looked at the code and tried to build it, it gives a bunch of errors. I think it's a mapping issue mainly in the mixin folder.

![image](https://user-images.githubusercontent.com/83538449/149985326-b209a55d-3df0-4bcf-8f6b-22d4385b8d50.png)

**Comment by LambdAurora** [comment]
You need Java 17 to compile this mod, it is the standard for 1.18 mods.

If you just want to grab a build, you can use the GitHub actions, Artifacts are uploaded there for every commits.

**Comment by gokayerez** [comment]
Thank you T.T apologies
