### ISSUE TITLE
Can't build the gradle, missing java information

### ISSUE THREAD

**Issue by lxly9** [LambdAurora/AurorasDecorations#24]
Hii, so as my title states IntelliJ can't build the gradle because the file is lacking information about it's desired java version. This is the error message im getting. (also im really really new to this whole thing but really love your mod and would love to play with it!)
[error.txt](https://github.com/LambdAurora/AurorasDecorations/files/8482211/error.txt)

**Comment by LambdAurora** [comment]
if you just want to play, please download from the GitHub actions: https://github.com/LambdAurora/AurorasDecorations/actions

Latest artifacts: https://github.com/LambdAurora/AurorasDecorations/suites/5913097735/artifacts/201814364

As far as I'm aware I cannot tell to anything that the build.gradle requires Java 17 to work, only that the built application requires Java 17.

**Comment by lxly9** [comment]
Ah thankies!! But I sadly need the mod for 1.18.1 and the mod's version is 1.18.2 :( thanks for your help though!!

**Comment by lxly9** [comment]
I assume its not possible for it to be migrated right?

**Comment by LambdAurora** [comment]
There was an older version for 1.18.1, but I don't even know how to find it in the actions tbh.
And no, migrating is not possible.

**Comment by lxly9** [comment]
Aw sad, thank you for your help!!!
