### ISSUE TITLE
Texture missing in Table stump

### ISSUE THREAD

**Issue by lostopkk** [LambdAurora/AurorasDecorations#32]
![image](https://user-images.githubusercontent.com/50776714/188343030-13962e12-7d38-4194-beed-0b8eeda1d6e9.png)

the log: https://mclo.gs/VoRMi88

**Comment by LambdAurora** [comment]
So, I started debugging the issue, it's fixed locally.

And I have this to say: **why the fuck did I needed 4GB of allocated RAM to even load a world with this mod?**
