### ISSUE TITLE
Add hanging signs

### ISSUE THREAD

**Issue by strawberry-kitten** [LambdAurora/AurorasDecorations#36]
I'm wondering if you could add in the hanging signs coming in the 1.20 update as I think they would fit well in this mod

**Comment by LambdAurora** [comment]
No.

Just wait for 1.20.
1.20 actually crushed any chance for this block to make into this mod.

Clarification: I don't find interest in adding a feature that will have to be removed anyway once the mod is updated to the new version. And if it's to work on my own take and have people disappointed once the release happens, not worth it.

**Comment by strawberry-kitten** [comment]
No need to get aggressive
