### ISSUE TITLE
[1.19.2] Sign post incompatibility with Sodium *without* Indium

### ISSUE THREAD

**Issue by Ampflower** [LambdAurora/AurorasDecorations#44]
## Steps to Reproduce
 - Install Sodium
 - Install AurorasDeco
 - Place a sign on a fence post

## Expected results
It to render perfectly fine

## Actual results
The game immediately crashes with a stack to getQuads not being able to extract the cardinal directions from the sign post, for as it isn't the fence post it was expecting.

## Extra
Discussed in Discord around [here](https://canary.discord.com/channels/734886100388151378/814091199010177024/1049758463179362304).

It is possible to quickly fix this by unwrapping the fence post from the sign post in the vanilla getQuads method, but I know this is not the intended fix. This does at least work for vanilla and should work for any other fence posts that don't require FRAPI to render it correctly, and any that do can depend on Indium or Indigo anyways.

The true fix would be the injector, tho, I know not how to actually implement it at all, let alone, correctly.

**Comment by LambdAurora** [comment]
Ok, I wasn't aware that it was *without* Indium.

Aurora's Decorations uses Fabric Renderer API thus requires Indium to work with Sodium.

**Comment by Ampflower** [comment]
Ah, fair. I mean, this managed pretty far without Indium surprisingly. I now kinda wonder if there's anything else I haven't ran into yet that could cause similar to this.

You could perhaps depend on NoIndium so you don't get... well, this again, unless you want to take the time for vanilla compatibility (or want me to, I'd be willing to go the extra mile where it's feasible, like here)
