### ISSUE TITLE
[Suggestion] Discard wood types with missing textures

### ISSUE THREAD

**Issue by foul-fortune-feline** [LambdAurora/AurorasDecorations#56]
Pretty much what it says on the tin. Mostly for compatibility with chipped so as not to flood an NEI-like (prolly datin myself there callin em that haha) or the recipe book with pink n black squares, but figured there is likely a way to make a general solution rather than special case, which would likely be less work (given the sheer number of blocks chipped adds), and broader compatibility, as IMO a decorative object being missing is usually better than it being glitched and present

**Comment by LambdAurora** [comment]
This is not technically feasible due to textures being a client-only concept that would cause issues with servers (and client-server synchronization).

**Comment by foul-fortune-feline** [comment]
Ah, I see. Thanks anyways
