### ISSUE TITLE
Backport to 1.16.5

### ISSUE THREAD

**Issue by ghost** [LambdAurora/AurorasDecorations#7]
I love this mod so much! But unfortunately, a lot of other fabric mod makers aren't porting their mods to 1.17 for the new update, and are just going to wait for 1.18. I REALLY wanna use this mod on my fabric server with my friends but my server has to stay on 1.16.5. I don't expect you to keep both versions updated or anything, but a simple 1.16.5 backport would be incredibly appreciated. Thanks!

**Comment by LambdAurora** [comment]
This mod is developed on 1.17 because of the new features and Java 16.

I am not willing to do a backport myself, if anyone wants to get a go at it they are free to do.
